server:
  port: 8081

spring:
  kafka:
    consumer:
      bootstrap-servers:
        - localhost:9092
       # - localhost:9093 // for docker containerized kafka use port 9093
      group-id: mygroup
      auto-offset-reset: earliest

    producer:
      bootstrap-servers:
        - localhost:9092
       # - localhost:9093 // for docker containerized kafka use port 9093